deploy:
  provider: heroku
  api_key:
    secure: VO4ErGeIi1X4InimjN/U94Mj0RSCMMdx7TbIv3lAgKFz7Ajy2rDT4FPx5K9PqVAKJ+hzUy255DpAYkHmeKSS2xqumM8WOsHtShZCy/2ScCfUmF5f5phDCbrCukTaSaouSJlBNXiLUWrhuZqMZGmupznKo4pgHYE99b1u63tdHGiMIAB95X1gvoMVy8eh0yWI9UTY9Xd+Tc347dBFrm55oJf2EpJYPNGjD08Pmv3ZIc+5ELFfx3kC0ujb8RU4+hByzttGV3cwreL3gRLL2Zc88FUS4eM5FSt10MW6u8BGsCwetXNoAu78HPYf0nf/QUIuju1Fn7gqymHLU5OzzNWdkAsai8AyBWLFxBzUoG/nPgx7trlCqJ8HsuJ7px8rDyAbHXIv/7PEqUkzhZ0v8sj7+x3ZGDekXQbjxB4EgjJ/piXfF+rO2eP8StLC4FyV0P1eSwQZtUIYa5A8TkRC2mqazpKY79XYLEaUaczXDuLAr5qqWpWYTymMBBVO1gagqRdXhBj3bK29BqT9Hn3/4D9KQiCxLQnfTxF0eMwYgeWRa8KBajP3jBKJVFVFEiOnk7t3/GQrSzO7x5gFd9BOIy03oEGLDm3uok+YSf3cauNogwwMFi/b2wM47RJ1NC13UdXlVQ2IVBl+GCRf6zkWQCAjQoW1f59Xy6E5GOOYIdzjL8M=
  app: hackaton-rails
  on: 
    branch: main
  run:
    - "rake db:migrate"
    - "rake db:seed"
  skip_cleanup: true